// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwt2oKHDXRJ1skx839StKJUYlK3MrPMzc',
    appId: '1:736591037754:web:e0904d861ec91ccb507c03',
    messagingSenderId: '736591037754',
    projectId: 'messagaty',
    authDomain: 'messagaty.firebaseapp.com',
    storageBucket: 'messagaty.appspot.com',
    measurementId: 'G-RSHWTN3VZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk2DPNGbst_YTsJWbd8macjIUh6xZHhO8',
    appId: '1:736591037754:android:c8ae582a1386ed59507c03',
    messagingSenderId: '736591037754',
    projectId: 'messagaty',
    storageBucket: 'messagaty.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJKvcPQnsrPj_aQ-ZQCaL_s0v07TpKejA',
    appId: '1:736591037754:ios:836b2147c0a0a6a6507c03',
    messagingSenderId: '736591037754',
    projectId: 'messagaty',
    storageBucket: 'messagaty.appspot.com',
    iosClientId: '736591037754-fr4av746b6tpj8rjt3lfh79pliur5e7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.messagaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJKvcPQnsrPj_aQ-ZQCaL_s0v07TpKejA',
    appId: '1:736591037754:ios:836b2147c0a0a6a6507c03',
    messagingSenderId: '736591037754',
    projectId: 'messagaty',
    storageBucket: 'messagaty.appspot.com',
    iosClientId: '736591037754-fr4av746b6tpj8rjt3lfh79pliur5e7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.messagaty',
  );
}
